# Generated by Django 6.0 on 2026-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(choices=[('Keyboard Navigation', 'Keyboard Navigation'), ('Screen Reader', 'Screen Reader'), ('Colour / Contrast', 'Colour / Contrast'), ('Text / Typography', 'Text / Typography'), ('Motion / Animation', 'Motion / Animation'), ('Other', 'Other')], max_length=100)),
                ('page_affected', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
