# Generated by Django 6.0 on 2026-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityissue',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
