# Generated by Django 6.0 on 2026-04-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_accessibilityissue_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityissue',
            options={'verbose_name': 'Accessibility', 'verbose_name_plural': 'Accessibility'},
        ),
    ]
