# Generated by Django 6.0 on 2026-03-17 12:56

import apps.esim_checker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESIMCheckerEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(help_text='Origin URL of the registered site (e.g. https://react.driverxmobile.com)', unique=True)),
                ('secret_key', models.CharField(default=apps.esim_checker.models.generate_secret_key, editable=False, help_text='Auto-generated 16-character secret key for this endpoint.', max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to block API calls from this site without deleting the record.')),
                ('hits_count', models.PositiveIntegerField(default=0, editable=False, help_text='Total number of successful API calls made from this site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_hit_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful API call.', null=True)),
            ],
            options={
                'verbose_name': 'eSIM Checker Endpoint',
                'verbose_name_plural': 'eSIM Checker Endpoints',
                'ordering': ['-created_at'],
            },
        ),
    ]
