# Generated by Django 6.0 on 2026-02-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_status_coupon_valid_from_coupon_valid_till_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit_per_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
