# Generated by Django 6.0 on 2026-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_limit_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='limit_per_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max uses per user. Leave empty = unlimited per user', null=True),
        ),
    ]
