# Generated by Django 6.0 on 2026-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='business_needs',
            field=models.CharField(max_length=50),
        ),
    ]
